version: "3"
services:
  redis_stack:
    image: redis/redis-stack:latest
    container_name: redis_stack
    # environment:
    #   REDIS_ARGS: --requirepass changeme
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - "./ignored/data:/data"
      # - "./ignored/redis-stack.conf:/redis-stack.conf"